/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.zhaw.it.cadprototyp;

import java.util.logging.Level;
import java.util.logging.Logger;

public class Main {

    private static final Logger logger = Logger.getLogger(Main.class.getCanonicalName());

    Main() {
        LogConfiguration.setLogLevel(Main.class, Level.FINE);
    }

    public static void main(String[] args) {
        logger.log(Level.FINEST, "Main started");
    }
}
